from tests import expected as expected, helpers as helpers
from typing import Any

def test_textio_sort(tmpdir: Any) -> None: ...
def test_textio_append(tmpdir: Any) -> None: ...
def test_auth_all_ok(mock_transmission: Any) -> None: ...
def test_auth_3_failed_attempts(mock_transmission: Any, nocolorcapsys: Any) -> None: ...
