import keyring.backend
from typing import Any

ALPHABET: Any

class KeyringTest(keyring.backend.KeyringBackend):
    priority: int = ...
    password: Any = ...
    def __init__(self) -> None: ...
    def set_password(self, servicename: Any, username: Any, password: Any) -> None: ...
    def get_password(self, servicename: Any, username: Any): ...
    def delete_password(self, servicename: Any, username: Any) -> None: ...

def mock_main(*args: Any) -> None: ...
def password_mocker(password: Any, stdin: Any): ...
def scramble_alphabet(): ...
def null_side_effect() -> None: ...
