from typing import Any

class NoColorCapsys:
    capsys: Any = ...
    def __init__(self, capsys: Any) -> None: ...
    @staticmethod
    def regex(out: Any): ...
    def readouterr(self): ...
    def stdout(self): ...
    def stderr(self): ...

def prep_path(dirname: Any, basename: Any): ...
def fixture_configdir(tmpdir: Any): ...
def fixture_cachedir(tmpdir: Any): ...
def fixture_categorpy_logs(categorpy_cache: Any): ...
def fixture_transmission_config(configdir: Any): ...
def fixture_categorpy_config(configdir: Any): ...
def fixture_categorpy_cache(cachedir: Any): ...
def fixture_transmission_settings(transmission_config: Any): ...
def fixture_make_loggers(mock_appdirs: Any, categorpy_logs: Any) -> None: ...
def fixture_nocolorcapsys(capsys: Any): ...
