"""
docs.conf
=========

Sphinx conf for categorpy docs
"""
import os
import sys

docs = os.path.abspath(".")  # noqa
repo = os.path.dirname(docs)  # noqa
package = os.path.join(repo, "categorpy")  # noqa
src = os.path.join(package, "src")  # noqa
sys.path.insert(0, docs)  # noqa
sys.path.insert(0, repo)  # noqa
sys.path.insert(0, package)  # noqa
sys.path.insert(0, src)  # noqa
import categorpy  # pylint: disable=C0413

# # -- Options for HTML output -----------------------------------------
# -- Project information -----------------------------------------------
project = categorpy.__name__  # pylint: disable=C0103
# noinspection PyShadowingBuiltins
copyright = categorpy.__copyright__  # pylint: disable=W0622,C0103
author = categorpy.__author__  # pylint: disable=W0622,C0103
release = categorpy.__version__  # pylint: disable=C0103
maintainer = categorpy.__maintainer__  # pylint: disable=C0103
email = categorpy.__email__  # pylint: disable=C0103
version = categorpy.__version__  # pylint: disable=C0103
# noinspection PyShadowingBuiltins
license = categorpy.__license__  # pylint: disable=W0622,C0103

# -- General configuration ---------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx.ext.autodoc",
    "sphinx.ext.imgmath",
    "sphinx.ext.doctest",
    "sphinxcontrib.programoutput",
    "sphinx.ext.githubpages",
    "sphinxcontrib.fulltoc",
]


# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"  # pylint: disable=C0103

# The master toctree document.
master_doc = "index"  # pylint: disable=C0103

# The language for content autogenerated by Sphinx. Refer to
# documentation for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None  # pylint: disable=C0103

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "monokai"  # pylint: disable=C0103

# -- Options for HTML output -------------------------------------------

# The theme to use for HTML and HTML Help pages. See the documentation
# for a list of builtin themes.
#

# Theme options are theme-specific and customize the look and feel of a
# theme further. For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets)
# here, relative to this directory. They are copied after the builtin
# static files, so a file named "default.css" will overwrite the builtin
# "default.css".

# Custom sidebar templates, must be a dictionary that maps document
# names to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}
# ---sphinx-themes-----
html_theme = "graphite"  # pylint: disable=C0103
html_domain_indices = True  # pylint: disable=C0103
html_use_index = True  # pylint: disable=C0103
html_show_sourcelink = True  # pylint: disable=C0103
html_show_sphinx = False  # pylint: disable=C0103
html_theme_path = ["_themes"]  # pylint: disable=C0103
html_sidebars = {
    "**": ["globaltoc.html", "searchbox.html"]
}  # pylint: disable=C0103

todo_include_todos = True  # pylint: disable=C0103
autoclass_content = "both"  # pylint: disable=C0103
autodoc_member_order = "bysource"  # pylint: disable=C0103
autodoc_default_options = {"members": None}  # pylint: disable=C0103
logo = "_static/icon.png"  # pylint: disable=C0103
add_function_parentheses = True  # pylint: disable=C0103
add_module_names = True  # pylint: disable=C0103
