import argparse
from typing import Dict, List

import transmission_rpc

from .auth import Keyring
from .find import Find
from .parser import Parser

KWARGS: Dict[str, str]
KEYRING: Keyring

def prior_auth(entered: int) -> None: ...
def prompt_save_password() -> None: ...
def instantiate_client() -> transmission_rpc.Client: ...
def run_client(unowned_magnets: List[str], unmatched: List[str]) -> None: ...
def start_transmission(magnets: Dict[str, str], unmatched: List[str]) -> str: ...
def transmission(argparser: Parser, find: Find) -> None: ...
