import os

from .log import get_logger as get_logger
from typing import Any, Union, Dict


class Config:
    def __init__(self) -> None:
        self.config_file: Union[bytes, str, os.PathLike] = ...
        self.app_config_dir: Union[bytes, str, os.PathLike] = ...
        self.user_config_dir: Union[bytes, str, os.PathLike] = ...
        self.client_dir: Union[bytes, str, os.PathLike] = ...
        self.settings_file: Union[bytes, str, os.PathLike] = ...
        self.ini: Any = ...
    def read_existing(self) -> None: ...
    def write_new(self) -> None: ...
    def _initialize_config(self) -> None: ...
    def read_json(self) -> Dict[str, str]: ...

def client_settings() -> Dict[str, str]: ...
