import logging
import sys

from . import log as log
from .locate import APPNAME as APPNAME
from typing import Any, Optional, Union


class AppErrs:
    def __init__(self, header: Any, **kwargs: Any) -> None:
        self.header: str = ...
        self.name: str = ...
        self.logger: logging.Logger = ...
        self.level: str = ...
        self.sendto: Union[sys.stdout, sys.stderr] = ...
        self.code: int = ...
    def summary(self, body: Optional[str] = ...) -> None: ...
    def log(self, msg: str, **kwargs: Any) -> None: ...

def exit_max_auth(tally: str) -> None: ...
def exit_fatal(err: Exception) -> None: ...
def terminate_proc() -> None: ...
def exit_error(err: Exception) -> None: ...
