import os

from .textio import TextIO as TextIO
from typing import Any, Union, List, Dict


class Torrents:
    def __init__(self, client_dir: Any) -> None:
        self.path: Union[bytes, str, os.PathLike] = ...
        self.files: List[Union[bytes, str, os.PathLike]] = ...
        self.obj: Dict[str, str] = ...
    def get_torrents(self) -> None: ...
    @staticmethod
    def _read_bencode_file(fullpath: Union[bytes, str, os.PathLike]) -> bytes: ...
    @staticmethod
    def _parse_bencode_object(bencode: bytes) -> str: ...
    def parse_torrents(self) -> None: ...

def index_path(paths_list: List[Union[bytes, str, os.PathLike]]) -> None: ...
