import os
from typing import Union

import appdirs

APPNAME: str

class AppDirs(appdirs.AppDirs):
    def __init__(self) -> None:
        super().__init__()
        self.user_config_dirname: Union[bytes, str, os.PathLike] = ...
        self.client_dir: Union[bytes, str, os.PathLike] = ...
    def _initialize_appdirs(self) -> None: ...

class AppFiles(AppDirs):
    def __init__(self) -> None:
        super().__init__()
        ...
        self.histfile: Union[bytes, str, os.PathLike] = ...
        self.blacklist: Union[bytes, str, os.PathLike] = ...
        self.paths: Union[bytes, str, os.PathLike] = ...
    def _initialize_appfiles(self) -> None: ...

APPDIRS: AppDirs
APPFILES: AppFiles
