from typing import Any

class NormalizeFile:
    def __init__(self, string: Any) -> None:
        self.string: Any = ...
    def normalize_whitespace(self) -> None: ...
    def normalize_non_alpha_numeric(self) -> None: ...
    def set_lowercase(self) -> None: ...
    def deduplicate_whitespace(self) -> None: ...
    def normalize(self) -> None: ...

class NormalizeMagnet:
    def __init__(self, magnet: Any) -> None:
        self.magnet: str = ...
    def remove_equals(self) -> None: ...
    def remove_last_delim(self) -> None: ...
    def remove_underscore(self) -> None: ...
    def remove_quotes(self) -> None: ...
    def remove_tuple(self) -> None: ...
    def normalize(self) -> None: ...
