from typing import Any, List


class Pages:
    def __init__(self, url: Any, pageno: Any) -> None:
        self.url: str = ...
        self.pageno: str = ...
        self.ulist: List[str] = ...
        self.ispage: bool = ...
        self.page_index: int = ...
        self.start: int = ...
        self.stop: int = ...
    def _set(self) -> None: ...
    def check_for_pages(self) -> None: ...
    def _replace_page(self, page_number: int) -> None: ...
    def select_page_number(self, page_number: int) -> str: ...
    def get_page_number(self) -> None: ...
    def intervals(self) -> None: ...
