import bs4

from . import exception as exception
from .normalize import NormalizeMagnet as NormalizeMagnet
from typing import Any, List


class ScrapeWeb:
    def __init__(self) -> None:
        self.soup: bs4.BeautifulSoup = ...
        self.magnets: List[str] = ...
        self.object: Any = ...
    def process_request(self, search: str) -> None: ...
    def scrape_magnets(self) -> None: ...
    def parse_magnets(self) -> None: ...
    def get_scraped_keys(self) -> List[str]: ...
